name: CI/CD with GCC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y g++

    - name: Build
      run: g++ cpp.cpp -o my_program

    - name: Test
      run: ./my_program
      
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_program
        path: ./my_program
